[package]
name = "mtgsdk"
version = "0.1.0"
authors = ["rogertorres <rogertps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
